/** Generated by create-hedgerow __HEDGEROW_GENERATOR_VERSION__. This file is yours to edit. */
export default {
  authorDid: "__HEDGEROW_AUTHOR_DID_JSON__",
  siteUrl: "__HEDGEROW_SITE_URL_JSON__",
  siteName: "__HEDGEROW_SITE_NAME_JSON__",
  editorPath: "/sudo",
};
